#!/bin/bash -e
#
# Please have a look at the Paragon Dev Documentation first to get a better
# idea about what this script does and how it works with the overlay files.
# Then take a look at the overlay files in the Files tab, then come back and
# edit this script.
#
# This script is executed at the end of appliance creation.  Here you can do
# one-time actions to modify your appliance before it is ever used, like
# removing files and directories to make it smaller, creating symlinks,
# generating indexes, etc.
#
# The 'kiwi_type' variable will contain the format of the appliance
# (oem = disk image, vmx = VMware, iso = CD/DVD, xen = Xen).
#

# Read in some variables.
. /studio/profile

# Read in KIWI utility functions.
. /.kconfig

# Make sure we're at root. Just to be safe!
cd /

sed -i 's/openSUSE/SendigOS/' /etc/default/grub

# We're finished!
exit 0
